---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[coderwall-chef-cookbook::default]
    attributes:
  - name: server
    run_list:
      - recipe[coderwall-chef-cookbook::default]
    attributes: